### PR TITLE
Added Subset Sum solution

### PR DESCRIPTION
**Pull request by deytulsi18**
Added the solution for subset sum

### CODE REVIEW

**Comment by deytulsi18** [comment]
Please merge the pull request for #5

**Comment by uditswaroopa** [comment]
I have a problem with your pull request for #5 as the code is copied one, I request @singhayushh to kindly check it.

**Comment by singhayushh** [comment]
Please go through the #1 once again. I am accepting contributions to the Readme only 😅

**Comment by deytulsi18** [comment]
ok , no prob

**Pull request closed without merging**
