### PR TITLE
Updated READMe.md 

### PR DESCRIPTION
**Pull request by deytulsi18**
Added more algorithm names to the existing 64 in the list

### CODE REVIEW

**Comment by deytulsi18** [comment]
Please review the PR and merge it.

**Comment by deytulsi18** [comment]
I have added more algos to the READMe list

**Review by singhayushh — APPROVED** [review]

**Comment by singhayushh** [comment]
Thank you for your contributions!

**Comment by deytulsi18** [comment]
Welcome
I just wanted to contribute and learn about open source.
Thanks for co-operating
😁

**Pull request merged**
